### ISSUE TITLE
Accounts - address

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#10]
address lines not populating - its there in the edit screen but not on the overview

![Screenshot 2023-07-08 at 17-08-14 My Account 4Site Technologies](https://github.com/markendley/frste/assets/90736622/affa8e09-7d42-4514-b617-3d188a8e9999)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
can we bring the line under phone so it's in alignment with the other 2?

![Screenshot 2023-07-14 at 15-06-06 My Account 4Site Technologies](https://github.com/markendley/frste/assets/90736622/8acea5b6-b5da-421e-9449-b070698da1b3)

**Comment by markendley** [comment]
done
