### ISSUE TITLE
Accounts - orders

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#11]
it's splitting the whole order into multiple orders. All the items on the order need to stay within the one order panel.

**Comment by markendley** [comment]
done

**Comment by Treadstudio** [comment]
it is putting it in one order but when you hit "reorder: it is not bringing all the product lines in

**Comment by markendley** [comment]
The reason the the reorder button didn't work for you was because the products you had in that order don't exist anymore

but there is alot of work I gotta do to this script

So far I can make the re-order button add those products to the cart, but I'm still working on getting the correct variations

**Comment by Treadstudio** [comment]
we had it working on the original TuffStuff site didn't we? I remember trying it out....

**Comment by markendley** [comment]
Would you settle for the re-order button next to each indivudal item?

<img width="1021" alt="Screenshot 2023-07-17 at 8 14 20 pm" src="https://github.com/markendley/frste/assets/6570606/8d0e5621-5d9c-4a08-8536-1cac5dca9b20">

**Comment by Treadstudio** [comment]
that could work....button placement i'd but under the QTY in each row though...will look nicer. 

having trouble getting the script to bring them all in at once?

**Comment by markendley** [comment]
ready

remember, if a product no longer exists obviously you can't reorder it.

**Comment by Treadstudio** [comment]
can't see this update - logged in as me on the order - no reorder on the line items?

**Comment by markendley** [comment]
when I looked in your account all your previous orders were of products that no longer exist. So go buy something, then check the order page.

**Comment by Treadstudio** [comment]
need the shipping issue fixed to test this one...

**Comment by markendley** [comment]
ready

**Comment by Treadstudio** [comment]
nice! if we can make it so the product adds and the slide out cart opens like #45

**Comment by markendley** [comment]
sorry, still working in this one.
Need a break now

**Comment by markendley** [comment]
ready!
