### ISSUE TITLE
Product Page - product details 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#15]
need to add some padding under the module when there are no features added in....

![Screenshot 2023-07-08 at 17-16-53 Hot Dipped Gal Conduit Fitting Sweeping Bend 4Site Technologies](https://github.com/markendley/frste/assets/90736622/89d6b0d3-cabf-4091-abdc-8bb53a268524)

Need to make the lines still go full width if not all the row if filled. Also need to add padding on the right hand edge of the columns so the text doesn't run into each other. 

![Screenshot 2023-07-08 at 17-18-28 PVC Heavy Duty Solar Corrugated Conduit 4Site Technologies](https://github.com/markendley/frste/assets/90736622/bffb47bb-01d7-4042-83e6-43e83f92d47b)

**Comment by Treadstudio** [comment]
can we also make the degrees "o" display properly?

**Comment by markendley** [comment]
fixed

**Comment by markendley** [comment]
> can we also make the degrees "o" display properly?

You mean the degree symbol?

It seems to be working for me, can you gimme the url of the page you're looking at?
