### ISSUE TITLE
Product Page - mobile 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#17]
1. dropdown fields for selections are displaying blue

2. properties - weird that 4 show on slide 1 and then 5 on slide 2? Shouldn't it be the other way? ALso can we add a little bit of padding under the 1/2 and the related products module?

![1](https://github.com/markendley/frste/assets/90736622/3372c770-5eb1-453a-97fc-e98a83477836)

![2](https://github.com/markendley/frste/assets/90736622/abf3120b-9120-41f4-b80c-d5d5b2c13cd5)

![3](https://github.com/markendley/frste/assets/90736622/01c584df-d214-4f1a-a553-7e1981ac45ad)

**Comment by markendley** [comment]
all fixed

**Comment by Treadstudio** [comment]
i'm still getting the tables displaying weirdly...check on mobile this URL https://demoplatform.net/frste/product/low-smoke-zero-halogen-black-round-junction-box-2-way/

**Comment by markendley** [comment]
fixed
