### ISSUE TITLE
Product page - features - mobile 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#18]
blue box when you click the buttons

![5](https://github.com/markendley/frste/assets/90736622/741e8bcd-22cf-4140-a5be-25eb2c83e78f)

video isn't displaying in the frame?

![4](https://github.com/markendley/frste/assets/90736622/34df258a-bb28-4d3c-ae13-d3e13db50486)

**Comment by markendley** [comment]
I can't replicate the issue on my end

gotta url?

**Comment by Treadstudio** [comment]
https://demoplatform.net/frste/product/hot-dipped-gal-conduit/

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
IOS still glitchy....video doesn't display and when it does it isn't in the frame.

Android is good.

**Comment by markendley** [comment]
oh, iOS doesn't support WebM yet, so I had to upload an mp4 file.

Remember, phones don't like video in general unless those movie files are served on a streaming server
