### ISSUE TITLE
Product page - mobile - spacing

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#19]
spacing when the icons are present needs to be balanced  - add a little more space between the last one and the product details 

![6](https://github.com/markendley/frste/assets/90736622/080bb912-6ce6-4a96-8902-d4e276701cbf)

for product that dont have any icons - let's reduce the gap to the "approvals" by 15%

![1](https://github.com/markendley/frste/assets/90736622/286baf1d-eb2e-4b0e-b92a-51ba5ee42de2)

**Comment by markendley** [comment]
all fixed
