### ISSUE TITLE
Shop - filters 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#20]
need them to slide open into the page as opposed to a dropdown (like we normally do) - same for both desktop and mobile.

on mobile - the line needs to go the same width as the product tile

**Comment by Treadstudio** [comment]
bug - when you select a category and then go back to all, it's not updating. i went in direct from the homepage tiles and then tried to go "all"

**Comment by markendley** [comment]
> need them to slide open into the page as opposed to a dropdown (like we normally do) 

Like we did for Townsend?

(That might take a couple of hours).

**Comment by Treadstudio** [comment]
similar to this http://demoplatform.net/rg/project/

**Comment by Treadstudio** [comment]
ok with the time to do it.

**Comment by Treadstudio** [comment]
something like this...can have the box or not the checkbox....would be the same for the brand dropdown/filter

![Screenshot 2023-07-21 08 48 37](https://github.com/markendley/frste/assets/90736622/15ee637e-3d5d-47cc-a6a8-6d26b53dd961)

also no need to change the background image per category - we can just keep it generic across all the cats.

**Comment by markendley** [comment]
ready!

**Comment by Treadstudio** [comment]
ok so a couple of things to fix....

1. when the user goes to the tape, nothing shows - let's default so that all products show
2. when the user selects more than 1 category, it shows no products as it is trying to find products in both rather than displaying results from both if that makes sense
3. need to make the brand and product cat filters work independent of each other

**Comment by Treadstudio** [comment]
styling looks great!

**Comment by markendley** [comment]
ok. how's that?

**Comment by Treadstudio** [comment]
The function is working well! Can we push the updated demo site to the live environment?

**Comment by markendley** [comment]
done

**Comment by Treadstudio** [comment]
thanks mate
