### ISSUE TITLE
Cart page - mobile

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#24]
figures appearing at different sizes? 

![8](https://github.com/markendley/frste/assets/90736622/54a11368-485d-491a-8bda-1e4d1c895dc3)

does the apple pay just appear by default? can it be turned off?

**Comment by Treadstudio** [comment]
product details display messy? can we imrove? maybe like this? for long names - need to make sure the second line lines up correctly. 

product: product name
size: size
QTY/Pack: value 

![9](https://github.com/markendley/frste/assets/90736622/23a6e8fb-3d63-49e8-bee1-85a471c4405a)

**Comment by markendley** [comment]
how's that?

**Comment by Treadstudio** [comment]
better but still a bit weird....can we not get the product details to sit under "product" and run out

![frste](https://github.com/markendley/frste/assets/90736622/70d3e08f-720b-4093-a38d-7da44ebb9c0d)

**Comment by markendley** [comment]
sure

**Comment by markendley** [comment]
done
