### ISSUE TITLE
Slide out cart mobile

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#25]
same issue with product info as in #24 

![10](https://github.com/markendley/frste/assets/90736622/e7ee050f-b080-4e50-be97-ae587f2291f7)

**Comment by markendley** [comment]
ok, what do you think now

**Comment by Treadstudio** [comment]
not great...this is what I'm getting on my iphone running 15.x

![12](https://github.com/markendley/frste/assets/90736622/54b27f03-fe2d-4e7d-870a-aa334e3133cb)

this is in browser stack (16.4 IOS). Can we make all the info left aligned? 

![Screenshot 2023-07-17 09 00 19](https://github.com/markendley/frste/assets/90736622/d6300303-f619-4eb4-b694-337048dfd5a3)

**Comment by markendley** [comment]
alright, that oughta do it
