### ISSUE TITLE
Home Page - product categories

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#3]
numbers should be different per tile as per the taxonomy order in the backend (e.g. 01, 02, 03, 04 etc) Currently they are all showing "03"

![Screenshot 2023-07-08 at 16-46-18 4Site Technologiesons - Electrical Supplies - Cable Ties Copper Lugs Heatshrink](https://github.com/markendley/frste/assets/90736622/913f2882-eb0e-4232-ada6-708b9fbf0c34)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
what size image is best for these tiles?

**Comment by markendley** [comment]
500 x 500 pixels

What's most important is that they're deep etched

**Comment by markendley** [comment]
Populate the field "category image"

**Comment by Treadstudio** [comment]
just tried populating "hot dipped conduits" but nothing is showing front end?

Seems like it is pulling from the thumbnail instead?

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
thanks
