### ISSUE TITLE
hosting/dns logins

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#34]
https://syn07ee.syd5.hostyourservices.net:2083/ 

Username: sitetec4

password: ghPG-nD_52!N8

**Comment by Treadstudio** [comment]
logins to both DNS/hosting. still making updated on demosite....let me know when the cut off is today for changes ahead of upload tomorrow

**Comment by markendley** [comment]
OK https://4sitetech.com.au/ is live.
