### ISSUE TITLE
brand page - logo

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#37]
uploaded a new white svg and how it is going full screen? is there a bug or have we got a setting wrong on the SVG file?

![Screenshot 2023-07-17 at 09-28-40 Auscon Archives 4Site Technologies](https://github.com/markendley/frste/assets/90736622/368f6719-ed75-4c70-a6ec-a7a81f713229)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
thanks mate.
