### ISSUE TITLE
Home page - media tiles

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#4]
can you check the heights - they look not as tall as the design files? can you recheck and maybe Let's add a bit....

**Comment by Treadstudio** [comment]
![Screenshot 2023-07-08 at 16-47-26 4Site Technologiesons - Electrical Supplies - Cable Ties Copper Lugs Heatshrink](https://github.com/markendley/frste/assets/90736622/abe01ce5-7285-42dc-9d6b-423c285a7bc8)

**Comment by markendley** [comment]
fixed
