### ISSUE TITLE
related products - mobile

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#40]
bit of tweaking to do here...can we make the tiles bigger so that mainly 1 shows and you just see the edge of the second so you know to scroll? Similar to my shit mark up 

![13](https://github.com/markendley/frste/assets/90736622/115f487b-aa22-4634-83ef-f554f18e4edf)

**Comment by markendley** [comment]
I'll just downssze the text

**Comment by Treadstudio** [comment]
just need to check IOS - the middle tile is sitting down, android is ok. 

otherwise looks great!

**Comment by markendley** [comment]
fixed
