### ISSUE TITLE
PDF downloads on product pages 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#41]
need to add in spec sheet (PDF doc) downloads. We spoke about it ages ago. Basically next to properties, if the product has properties, or if not, in the main position add in "Spec Sheets". In the case of both being present, maybe we do the inactive state in the same grey as the shipping/price note. 

if the user clicks that, the properties tables move to show PDF link downloads.

![Screenshot 2023-07-17 at 16-59-52 ABS Conduit Connector 4Site Technologies](https://github.com/markendley/frste/assets/90736622/bc5bad91-605d-48d8-92e5-d1b6f7e32321)

**Comment by markendley** [comment]
ready

check out
https://demoplatform.net/frste/product/hot-dipped-gal-junction-box-2-way-angled/

**Comment by Treadstudio** [comment]
that's close. I actually want the spec sheets larger down where the larger "properties" is.....can we do that? Styling is good 

![Screenshot 2023-07-21 08 14 08](https://github.com/markendley/frste/assets/90736622/d2bf898e-72f5-48e6-aae6-31bad051a866)

**Comment by Treadstudio** [comment]
same line issue when only 1 sheet is present. top line needs to go full width as well 

![Screenshot 2023-07-21 at 10-58-46 Hot Dipped Gal Junction Box 2 Way Angled 4Site Technologies](https://github.com/markendley/frste/assets/90736622/881f6636-7fc7-47df-9bed-bf497ce82229)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
styling is good!

the actual sheets aren't showing on mobile though when you click into them....?

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
nope...now the "properties | Spec Sheets" heading isn't showing so you can't tab between them

**Comment by markendley** [comment]
You can't see these two tabs?

<img width="688" alt="Screenshot 2023-07-25 at 1 31 26 pm" src="https://github.com/markendley/frste/assets/6570606/fee7b767-8478-41b3-a172-cd02b1a2b764">

**Comment by Treadstudio** [comment]
Nope they have disappeared on desktop and mobile….

**Comment by Treadstudio** [comment]
![Screenshot 2023-07-25 13 35 09](https://github.com/markendley/frste/assets/90736622/5947f7bc-06f6-4421-a5ef-ab36aacb5e54)

**Comment by markendley** [comment]
You mean for all other products but this one?
https://demoplatform.net/frste/product/hot-dipped-gal-junction-box-2-way-angled/

**Comment by Treadstudio** [comment]
did you just update something? i can now see them on more products....

**Comment by markendley** [comment]
Not since last time

But theere is a little bug after all

https://demoplatform.net/frste/product/low-smoke-zero-halogen-black-round-junction-box-4-way/

The tabs will only show if there are BOTH downloads and specs, so I'm gonna fix that

**Comment by Treadstudio** [comment]
ahh yep that would explain it!

**Comment by Treadstudio** [comment]
obliviously if there are no spec sheets that tab doesn't need to show

**Comment by Treadstudio** [comment]
can you also check the text size for the doc name - it looks a little smaller than the subtext in the properties table. they should be the same

**Comment by markendley** [comment]
all done

**Comment by Treadstudio** [comment]
can you just check for when a data
