### ISSUE TITLE
product category tiles

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#42]
can we look to make a change closer to the proof?

![Screenshot 2023-07-17 19 42 17](https://github.com/markendley/frste/assets/90736622/087ad5c3-45a6-4f83-a72d-922314fa0481)

it'll help stop images getting cut off....

**Comment by markendley** [comment]
Sure

but you need to upload images that are deep etched (transparent background), and make the image cropp off by the right hand side.

Do that and I can take care of the rest

**Comment by markendley** [comment]
(I can change the image from color to grayscale)

**Comment by Treadstudio** [comment]
would they all have to crop right hand side? Tapes might be a bit hard to do that. I can give a couple of samples if that would help?

deep etched isn't a problem.

**Comment by Treadstudio** [comment]
Still 500 x 500?

**Comment by Treadstudio** [comment]
uploaded 3 into the media gallery for testing on thursday....latest 3 marked -feature.png

**Comment by markendley** [comment]
I can confirm that the image specifications work.

<img width="1138" alt="Screenshot 2023-07-20 at 5 19 15 pm" src="https://github.com/markendley/frste/assets/6570606/3d3d2cbe-be35-4ef3-b982-fbb710ea4b68">
