### ISSUE TITLE
Add new svg icon files into CMS

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#46]

**Comment by markendley** [comment]
sorry can you resend the illustrator file, I 'm seemed to have lost it

**Comment by Treadstudio** [comment]
just emailed to you

**Comment by markendley** [comment]
[SVG.zip](https://github.com/markendley/frste/files/12158101/SVG.zip)

**Comment by Treadstudio** [comment]
thanks - looks like we have a bug....

![Screenshot 2023-07-25 at 17-09-06 Hot Dipped Gal Junction Box 2 Way Angled 4Site Technologies](https://github.com/markendley/frste/assets/90736622/3f8872d0-98d0-4723-ad04-98316b1de046)

**Comment by markendley** [comment]
Ive set a max-width on those icons

**Comment by Treadstudio** [comment]
perfect! thanks
