### ISSUE TITLE
continuous brand scroll

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#5]
it's glitching and has a big gap between the start and end 

![Screenshot 2023-07-06 17 18 33](https://github.com/markendley/frste/assets/90736622/78844087-fa65-4b3b-a65d-56053ddc099c)

**Comment by markendley** [comment]
Oh, we're missing a logo for Firesafe

**Comment by Treadstudio** [comment]
yep got to add that in shortly! any particular size the logo should be?
