### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by markendley** [markendley/frste#54]
> See attached….noticed the $1.00 In Stock at the base of the search results….is there a way to stop that info needing through the meta data and into the search result preview?

> That $1.00 is just the dummy price inputted that WooCommerce requires (it’s not meant to be seen by the public…)

**Comment by markendley** [comment]
Hey, 

I did it to the live site as well.

Google hasn't picked up on it yet, but I checked the code and the price has certainly been removed from the Schema.

("schema" is a like an outline of specifications in the code (like SEO meta tags but in much more depth), by default the woocommece plugins auto-generates this)

**Comment by Treadstudio** [comment]
unreal. google has picked up the change. thanks!

**Comment by Treadstudio** [comment]
can you check for this? may have dropped the update when we pushed the demo to live? I'm seeing the price again in the results.

**Comment by markendley** [comment]
The code I put in last time is still there, I google a couple of products and they're not showing prices. What do you see?

**Comment by markendley** [comment]
Just refered to your original email:

OK I see that it's not showing prices for every product except this one..

<img width="929" alt="Screenshot 2023-08-03 at 11 48 52 am" src="https://github.com/markendley/frste/assets/6570606/561c5ff6-a0bc-4b48-a0db-8eb96f46da58">

It must just be google, sometimes it takes a while for google to pick things up..

**Comment by markendley** [comment]
Maybe I can just adjust the XML sitemap file to just hide all the products from the search engines just to be safe?

**Comment by Treadstudio** [comment]
Na don't do that! Need the products to be visible.

All good. I'll just keep an eye on it for now.
