### ISSUE TITLE
product pages

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#62]
holder text on the options has disappeared...

see staging

![Screenshot 2023-08-07 at 20-28-17 Metal Cable Gland with Locknut 4Site Technologies](https://github.com/markendley/frste/assets/90736622/ffccaf4e-fa89-4fb7-8828-86377734219d)

versus live 

![Screenshot 2023-08-07 at 20-27-35 Metal Cable Gland with Locknut 4Site Technologies](https://github.com/markendley/frste/assets/90736622/46495289-1509-46ce-8f33-6fd4c5712966)

**Comment by markendley** [comment]
What am I exactly am I looking at?
... "Choose an option" ?

I had to reset that section to fix the cart slide-out.

**Comment by markendley** [comment]
No "Choose an Option"

**Comment by Treadstudio** [comment]
correct it needs to show the attribute name (e..g Thread Size, Size, Colour) etc. like in the second screenshot

**Comment by markendley** [comment]
done
