### ISSUE TITLE
Cart Page

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#7]
1. QTY fields should be on black background.

2. alignment issue with subtotal etc. compared to table above.

3. can we make the totals, subtotals etc show like this if thousands $11,000?

4. when the update cart button appears can we place it down where shown?

![Screenshot 2023-07-08 at 16-54-49 Cart 4Site Technologies](https://github.com/markendley/frste/assets/90736622/67698252-73af-41ee-ad12-293931b4f130)

**Comment by markendley** [comment]
all done.

> when the update cart button appears can we place it down where shown?

I've made it so the cart will automanically update when the QTY changes

**Comment by Treadstudio** [comment]
the auto update isn't working on my machine, can take a video if needed?

**Comment by markendley** [comment]
No it's ok, it's a server problem
.... I might just move the "Update cart" button down after all.

**Comment by Treadstudio** [comment]
strange, it was originally auto updating but the button came up as well if that makes sense.

do you want me to try it on the live server environment?

**Comment by markendley** [comment]
nah it's ok, leave it with me

**Comment by markendley** [comment]
fixed
