### ISSUE TITLE
Search results - view all results 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#70]
the sorting drop downs are displaying and can't be closed. ideally just the products should display. also let's adjust the padding for the words next to the filters so it doesn't look so tight. 

![Screenshot 2023-08-13 at 12-08-25 You searched for saddle 4Site Technologies](https://github.com/markendley/frste/assets/90736622/5a874ff8-f18a-4e8b-a8be-2c1a71ae3a3b)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
not seeing this update. still getting same result

**Comment by markendley** [comment]
Really?

Whenever I land on a search results page like https://demoplatform.net/frste/?s=orange

the Search filter options close

**Comment by Treadstudio** [comment]
Try searching “cable” – see back half of this video

https://www.loom.com/share/3ddc7fa9b6be43efaef655b97310b1b7?sid=03c6c41b-b426-48c5-98b6-1551154ceccd

**Comment by markendley** [comment]
thanks

fixed
