### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#72]
only pulling in the email form field into the user card in the CMS.

also can we change the page the form redirects to?

**Comment by markendley** [comment]
You're talking about the registration form?

<img width="652" alt="Screenshot 2023-09-14 at 2 36 44 pm" src="https://github.com/markendley/frste/assets/6570606/1b2e8526-4108-4962-8508-f4da18eb1e1d">

<img width="793" alt="Screenshot 2023-09-14 at 2 41 44 pm" src="https://github.com/markendley/frste/assets/6570606/6c68ee7c-968c-4d69-bfbf-5e605f8f002c">

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
Looks good…thanks!
