### ISSUE TITLE
spec sheets

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#73]
the tables aren't displaying on mobile?

![4Site-Spec-no-show](https://github.com/markendley/frste/assets/90736622/d3aaab99-33dc-4ab9-aa4c-bf2b273db443)

**Comment by markendley** [comment]
made an amendment, tested a couple of pages
Is it working for you now, otherwise send me the url of the page your looking at

**Comment by Treadstudio** [comment]
yep that worked
