### ISSUE TITLE
related products

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#74]
on a product page that has no 'properties' showing the "related products" wording is in white

https://demoplatform.net/frste/product/bell-mouth-bi-metal-copper-aluminium-lugs/

https://demoplatform.net/frste/product/stainless-steel-cable-tie-gun/

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
sorry mark, not the background - the background stays the same colour it was before.

it was just the words 'related products' that was showing in white and should have been in black

**Comment by markendley** [comment]
fixed
