### ISSUE TITLE
Add Approvals Tab to product page 

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#75]
see mock up. Need to add an "Approvals" tab option to the product page.

It needs to support PDF docs like the Spec Sheets tab does 

![Screenshot 2023-10-03 11 16 54](https://github.com/markendley/frste/assets/90736622/dc608326-9947-4bda-9a7d-dc224207c981)

**Comment by markendley** [comment]
ready

**Comment by markendley** [comment]
you'll see a new set of field called "Approvals"

**Comment by Treadstudio** [comment]
working great for products that show properties, spec sheets and now approvals

https://demoplatform.net/frste/product/low-smoke-zero-halogen-black-adaptable-box/

on products that just have spec sheets an approvals showing it's glitching 

https://demoplatform.net/frste/product/bell-mouth-bi-metal-copper-aluminium-lugs/

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
working...only thing is on hover it shows a cursor not a hand indicating click to take action...?
