### ISSUE TITLE
Slide out cart

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#8]
1. fix text alignment issue on product name and can be do the same look for the figures (e.g. $1,200)
2. can we show GST and grant total as well?
3. need to add in continue shopping link (ref proof)

**Comment by Treadstudio** [comment]
![Screenshot 2023-07-08 at 16-57-55 4Site Technologiesons - Electrical Supplies - Cable Ties Copper Lugs Heatshrink](https://github.com/markendley/frste/assets/90736622/f1502d29-4d37-4f52-a19f-62222a3dbb27)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
still needs a bit of refinement on placement

![Screenshot 2023-07-16 20 00 41](https://github.com/markendley/frste/assets/90736622/a8362879-3895-4293-a049-b55c0602729c)

**Comment by markendley** [comment]
done

**Comment by Treadstudio** [comment]
can we add a little padding so the product name doesn't go so close to the price. 

![Screenshot 2023-07-18 at 08-51-14 4Site Technologies](https://github.com/markendley/frste/assets/90736622/478db485-6afb-423a-bb43-be8c8aa0930b)

**Comment by markendley** [comment]
fixed
